moai:
  initialized: true
  initialized_at: '2025-12-19T00:00:00Z'
  version: 1.14.5
project:
  name: bom-ABA-edu-portal
  mode: personal
  description: ''
  created_at: '2026-02-09 14:17:19'
  template_version: 1.14.5
  optimized: false
